_target_: src.models.GCnet_module.GCnetLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0005
  weight_decay: 0.05

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

scheduler_monitor: "valid/loss"
scheduler_interval: "epoch"
scheduler_frequency: 1


net:
  _target_: pytorchGAT.models.definitions.GAT.GAT
  node_number: 50
  embedding_size: 128
  num_of_layers: 2
  num_heads_per_layer: [8,1]
  num_features_per_layer: [128, 64, 128]
  dropout: 0.1
  last_layer_dim: [64, 2]
  is_prob: True

# compile model for faster training with pytorch 2.0
compile: false

DataVersion: ""
